name: CI
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - run: yarn install --immutable

      - run: yarn nx affected -t lint test:vitest build --base=origin/main --head=HEAD